#include <stdio.h>

/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main() {
	printf("Problem 2 - Even Fibonacci numbers\n");
	int num0 = 1;
	int num1 = 1;
	int temp = 0;
	int sum = 0;
	while (num1 < 4000000) {
		temp = num1;
		num1 += num0;
		num0 = temp;
		if (!(num1 & 1))
			sum += num1;
	}

	printf("The sum of all the terms in the Fibonacci sequence whose values do not exceed four million is %d\n", sum);
	return 0;
}
