#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/*
    Pentagonal numbers are generated by the formula, Pn = n(3n-1)/2. The first ten pentagonal numbers are:

        1,5,12,22,35,51,70,92,117,145,...

    It can be seen that P4 + P7 = 22+70 = 92 = P8. However, their difference, 70-22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D=|Pk-Pj| is minimised; what is the value of D?
*/

int is_pentagonal(int n) {
    double result = (1 + sqrt(24*n + 1)) / 6;
    return floor(result) == result;
}

int pentagonal(int n) {
    return n * (3*n - 1) / 2;
}

int main() {
    int max = 10000;
    for (int j = 1; j < max; j++) {
        for (int k = j + 1; k < max; k++) {
            unsigned long long Pj = pentagonal(j);
            unsigned long long Pk = pentagonal(k);

            if (is_pentagonal(Pj + Pk) && is_pentagonal(Pk - Pj)) {
                printf("%lld\n", Pk - Pj);
                return 0;
            }
        }
    }

    return 0;
}