#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/*
    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

    Triangle    Tn = n(n+1)/2
        
    Pentagonal  Pn = n(3n-1)/2
        
    Hexagonal   Hn = n(2n-1)
        
    It can be verified that T285 = P165 = H143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.
*/

int is_triangle(unsigned long long n) {
    double result = (-1 + sqrt(8*n + 1)) / 2;
    return floor(result) == result;
}

int is_pentagonal(unsigned long long n) {
    double result = (1 + sqrt(24*n + 1)) / 6;
    return floor(result) == result;
}

unsigned long long hexagonal(unsigned long long n) {
    return n * (2 * n - 1);
}

int main() {
    unsigned long long n = 144;
    unsigned long long hexagonalNumber = hexagonal(n);

    while (!is_triangle(hexagonalNumber) || !is_pentagonal(hexagonalNumber)) {
        n++;
        hexagonalNumber = hexagonal(n);
    }

    printf("%lld : %lld\n", n, hexagonalNumber);

    return 0;
}